#! /usr/bin/env python
# vi: set syntax=python : */

import findrox
import rox

from rox.Menu import Menu, set_save_name
 
set_save_name('Dome')

no_gui_mode = 0

# Ugly hack to stop wierd chars appearing...
#import xml.dom.html
#xml.dom.html.HTML_CHARACTER_ENTITIES = {}

import sys
from os.path import dirname

app_dir = dirname(sys.argv[0])

from rox import g
from Window import Window

#sys.argv.append('--disable-crash-dialog')
#import gnome.ui
#sys.argv.pop()

if len(sys.argv) > 1:
	files = sys.argv[1:]
	del sys.argv[1:]		# GnomeCanvas can't cope with -
	win = apply(Window, files)
else:
	win = Window()

win.show()

#import profile
#profile.run('rox.mainloop()')

rox.mainloop()
