#! /usr/bin/env python
# vi: set syntax=python : */

import findrox

# Ugly hack to stop wierd chars appearing...
import xml.dom.html
xml.dom.html.HTML_CHARACTER_ENTITIES = {}

import sys
from os.path import dirname

app_dir = dirname(sys.argv[0])

import gtk
from Window import Window

tl_windows = 0

import signal

import debug
signal.signal(signal.SIGINT, debug.debug_prompt)

def tl_ref(w = None):
	global tl_windows
	tl_windows = tl_windows + 1

def tl_unref(w = None):
	global tl_windows
	tl_windows = tl_windows - 1
	if tl_windows < 1:
		gtk.mainquit()

docs = []

if len(sys.argv) > 1:
	files = sys.argv[1:]
	del sys.argv[1:]		# GnomeCanvas can't cope with -
	for file in files:
		win = Window(file)
		win.connect('destroy', tl_unref)
		tl_ref()
		win.show()
else:
	win = Window()
	win.connect('destroy', tl_unref)
	tl_ref()
	win.show()

if tl_windows > 0:
	#import profile
	#profile.run('mainloop()')

	gtk.mainloop()
